### ISSUE TITLE
Fixing no result display for the tables

### ISSUE THREAD

**Issue by yookoala** [GibbonEdu/module-higherEducation#3] opened 2019-03-08 06:48 UTC
The no result message should not be handled by `$page->addError()` calls.

As @rossdotparker pointed out:
> The use of $page for errors is placing the error at the top of the page, rather than (in the case below) by the table:
> 
> <img alt="screenshot 2019-03-08 at 1 56 08 pm" width="1315" src="https://user-images.githubusercontent.com/5436438/54010559-33c05800-41aa-11e9-82e4-e11a3aba30e3.png">

Before GibbonEdu/core#686 or equivalent implementation is in the mainline, we can simply refactor all tables here to display a row with the "no result" message in it.

**Comment by rossdotparker** [comment] 2019-03-08 14:17
Hi Koala, I am going to close this for now, as the issue is solved for now, and we can come back and refactor when we address the issue in the core. Does that sound OK? Let me know if you want me to reopen it. Thanks : )

**Closed by rossdotparker** 2019-03-08 14:17 UTC

**Comment by SKuipers** [comment] 2019-03-11 01:56
Thanks for looking into this! Looks like the tables in this page haven't been refactored yet, so it ended up being a matter of mixing newer code with older tables. I agree Koala, once refactored the `DataTable` class handles these messages, rather than using the `$page` variable.
